name: sleep_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^9.3.0
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.1
  alarm: ^5.0.2
  shared_preferences: ^2.5.2
  flutter_localizations:
    sdk: flutter
  intl: any
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  auto_route_generator: ^9.3.1
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icon.png"
  image_path: "assets/icon.png"

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/alarm.mp3
